name: Generate OpenAPI Map

on:
  workflow_dispatch:
    inputs:
      commit_changes:
        description: "Commit and push changes if map files are updated"
        required: true
        type: boolean
        default: true

jobs:
  generate-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Ensure output directory exists
        run: |
          mkdir -p public/open-api
          ls -la public/open-api

      - name: Generate OpenAPI map
        run: npm run generate:openapi-map

      - name: List generated files
        run: |
          echo "Contents of public/open-api:"
          ls -la public/open-api/
          echo "File contents:"
          cat public/open-api/all.json || echo "File not found"

      - name: Check for changes
        id: git-check
        run: |
          echo "Current git status:"
          git status

          echo "Adding files to git:"
          git add public/open-api/*.json

          echo "Git status after adding:"
          git status

          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true' && inputs.commit_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update OpenAPI map specifications [skip ci]"
          git push
