name: Generate OpenAPI Map

on:
  workflow_dispatch:
    inputs:
      commit_changes:
        description: "Commit and push changes if map files are updated"
        required: true
        type: boolean
        default: true

jobs:
  generate-map:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Ensure output directory exists
        run: mkdir -p public/open-api

      - name: Generate OpenAPI map
        run: npm run generate:openapi-map

      - name: Check for changes
        id: git-check
        run: |
          echo "Current git status:"
          git status

          git add public/open-api/*.json

          echo "Git status after adding:"
          git status

          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in OpenAPI map"
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected in OpenAPI map"
          fi

      - name: Debug conditions
        run: |
          echo "changes = ${{ steps.git-check.outputs.changes }}"
          echo "commit_changes = ${{ inputs.commit_changes }}"
          echo "Combined condition = ${{ steps.git-check.outputs.changes == 'true' && inputs.commit_changes }}"

      - name: Commit and push changes
        if: ${{ steps.git-check.outputs.changes == 'true' }}
        run: |
          echo "Attempting to commit changes..."
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update OpenAPI map specifications [skip ci]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push
          echo "Changes committed and pushed successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
